#!/usr/bin/env python3

#https://blog.kiyohiroyabuuchi.com/en/dft-en/vasp-calculation-of-nudged-elastic-band-neb-2/
# https://workshop.materialsproject.org/lessons/03_heterointerfaces/Main%20Lesson/

from pymatgen.core.structure import Molecule, Structure
from pymatgen.io.vasp.outputs import Vasprun, Poscar
from pymatgen.core.surface import SlabGenerator, Slab

a_fe = 2.833 # PBE

def surface_transformation():
    from pymatgen.transformations.advanced_transformations import AddAdsorbateTransformation, SlabTransformation
    fe_bcc = Structure.from_file('./1_Fe_bcc/CONTCAR')
    vr = Vasprun('./1_Fe_bcc/vasprun.xml', parse_potcar_file = True)
    str = vr.get_computed_entry().structure
    
    slacFe = SlabTransformation((1,1,1), 1, 1, lll_reduce=True, 
            center_slab=False, in_unit_planes=True, primitive=True, 
            max_normal_search=2, shift=0, tol=0.1)
            
    adsorbate = Molecule(['H'], coords=[(0,0,0)])
    ads = AddAdsorbateTransformation(adsorbate, selective_dynamics=True, height=1.0, 
            mi_vec=None, repeat=None, min_lw=5.0, translate=True, 
            reorient=False, find_args=None)
    slab = slabFe.apply_transformation(str)
    slab = ads.apply_transformation(slab, return_ranked_list=False)
    
#============== Method #1

str = Structure.from_file('./1_Fe_bcc/CONTCAR')

slabFe = SlabGenerator(str,
                        miller_index=(1,1,0),
                        min_slab_size=9, in_unit_planes = True,
                        min_vacuum_size=8, primitive  = False,
                        center_slab=False)

slab = slabFe.get_slabs()
print(len(slab), slab[0])
slab[0].to(fmt= 'poscar', filename='POSCAR')
